name: Taiwan News Scraper
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual trigger button
jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install axios xml2js firebase-admin dotenv date-fns @opentelemetry/api
      - name: Create Service Account Key
        # This converts your Secret back into a JSON file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > serviceAccountKey.json
      - name: Run Scraper
        run: node scripts/scrape-and-upload.js
